### ISSUE TITLE
Unable to upload to blob error:  java.lang.IllegalArgumentException: Address  is a relative address. Only absolute addresses are permitted.  >>at com.microsoft.azure.storage.StorageUri.AssertAbsoluteUri(StorageUri.java:34)  >>at com.microsoft.azure.storage.StorageUri.setPrimaryUri(StorageUri.java:183)  >>at com.microsoft.azure.storage.StorageUri.<init>(StorageUri.java:105)  at com.microsoft.azure.storage.StorageUri.<init>(StorageUri.java:49)  >>at com.microsoft.azure.storage.blob.CloudBlockBlob.<init>(CloudBlockBlob.java:96)

### ISSUE THREAD

**Issue by lanrehnics** [Azure/azure-storage-android#18]
//When I click on the button it called the code below..
// then this launches an intent of file picker..

public void browseFile(View view) {

        Intent intent = new Intent(Intent.ACTION_GET_CONTENT);
        intent.setType("file/*");
        startActivityForResult(intent, SELECT_PICTURE);

    }

//After  it calls the on activity result
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {

        if (resultCode == RESULT_OK) {
            switch (requestCode) {

                case SELECT_PICTURE:

// the filepath is a Uri variable
                    filepath = getRealPathFromURI(Upload.this, data.getData());
                    filePath.setText(filepath);

                    break;

            }
        }

    }

// this method help get the real path
    public String getRealPathFromURI(Context context, Uri contentUri) {
        Cursor cursor = null;
        try {
            String[] proj = {MediaStore.Images.Media.DATA};
            cursor = context.getContentResolver().query(contentUri, proj, null, null, null);
            int column_index = cursor.getColumnIndexOrThrow(MediaStore.Images.Media.DATA);
            cursor.moveToFirst();
            return cursor.getString(column_index);
        } finally {
            if (cursor != null) {
                cursor.close();
            }
        }
    }

//then here is the uploading code
 public void uploadPhoto(View view) {
        if (mClient == null) {
            return;
        }
        linearOverlay.setVisibility(View.VISIBLE);
        txt_notifyier.setText("Inserting");
        // Create a new item
        final Uploads item = new Uploads();
        item.setVersion(et_uploadVersion.getText().toString().toLowerCase());
        item.setContainerName("todoitemimages");
        item.setName(et_uploadName.getText().toString().toLowerCase());
        // Use a unigue GUID to avoid collisions.
        UUID uuid = UUID.randomUUID();
        String uuidInString = uuid.toString();
        item.setResourceName(uuidInString);

        ListenableFuture<Uploads> entity = mUploads.insert(item);
        Futures.addCallback(entity, new FutureCallback<Uploads>() {
            @Override
            public void onSuccess(final Uploads result) {

                try {

                    et_generatedUploadLink.setText(result.getImageUri());
                    // If we have a returned SAS, then upload the blob.
                    if (result.getSasQueryString() != null) {

                        // Get the URI generated that contains the SAS
                        // and extract the storage credentials.
                        Thread myThread = new Thread(new Runnable() {

                            @Override
                            public void run() {
                                try {
                                    Upload.this.runOnUiThread(new Runnable() {
                                        @Override
                                        public void run() {
                                            txt_notifyier.setText("Uploading");
                                        }
                                    });
                                    StorageCredentials cred =
                                            new StorageCredentialsSharedAccessSignature(result.getSasQueryString());
                                    URI imageUri = new URI(result.getImageUri());

                                    // Upload the new image as a BLOB from a stream.
                                    CloudBlockBlob blobFromSASCredential =
                                            new CloudBlockBlob(imageUri, cred);

                                    blobFromSASCredential.uploadFromFile(filepath);
                                    Upload.this.runOnUiThread(new Runnable() {
                                        @Override
                                        public void run() {

                                            txt_notifyier.setText("Finish");
                                            linearOverlay.setVisibility(View.GONE);
                                        }
                                    });
                                } catch (final Exception ee) {
                                    runOnUiThread(new Runnable() {
                                        @Override
                                        public void run() {
                                            ee.printStackTrace();
                                            filePath.setText("Message:  " + ee.getMessage() + "\n\n" + "Cause:  " + ee.getCause());
                                            linearOverlay.setVisibility(View.GONE);
                                        }
                                    });

                                }

                            }
                        });
                        myThread.start();

                    }

                } catch (final Exception e) {
                    e.printStackTrace();
                    filePath.setText("Message:  " + e.getMessage() + "\n\n" + "Cause:  " + e.getCause());
                    linearOverlay.setVisibility(View.GONE);
                }
            }

            @Override
            public void onFailure(Throwable t) {

            }
        });

    }

**Comment by emgerner-msft** [comment]
As the exception message says, 'Address is a relative address. Only absolute addresses are permitted. '. So, when you're creating the block blob, you're creating with a relative address rather than an absolute address. Ie, result.getImageUri() is returning a partial rather than full address. If you step-through debug you'll be able to see this. Make sure the URI you pass has a form something like https://myaccount.blob.core.windows.net/mycontainer/myblob

**Comment by lanrehnics** [comment]
The link you drop is dead..

**Comment by emgerner-msft** [comment]
Yes, this is an example of a url format, not meant to be clicked. Please compare the URL you are passing to the method with that form, substituting of course 'myaccount' for your account name, 'mycontainer' for your container name, and 'myblob' for your blob name.

**Comment by lanrehnics** [comment]
Am uploading via mobile service.. Please Every is generated i cloud.. The Relative address is it the address of the file I want to upload .. Or the imageUri .... Or Please can yu write a tutorial that make one select a local file and upload to azure instead of taking a picture.. Please walk  me through cos I pritty much need it very sooon..

**Comment by emgerner-msft** [comment]
result.getImageUri() >> I don't know what this outputs so I can't do anything to help you. This needs to be an absolute address, like the example I gave. This should be the URI of the blob you want to upload to.

**Comment by emgerner-msft** [comment]
@lanrehnics  Haven't heard anything since Oct so closing this issue. Feel free to reopen with any follow up or open a new issue if you have additional questions.
