### ISSUE TITLE
No Progress info while uploading file to azure blob storage.

### ISSUE THREAD

**Issue by ManuBabu** [Azure/azure-storage-android#36]
Hi,

I am using azure blob storage in my android app to store files.
for uploading the files from android phone to blob storage i am using "CloudBlockBlob" instance
Example:-  "cloudBlockBlob.uploadFromFile(File_Path,File_Uri)

issue: 
1.i am not able to get upload progress on upload action.
2. if upload fails due to some network issues not able to get the report.
3. no acknowledge report after upload completed.

please help me with this.

**Comment by jofriedm-msft** [comment]
Hi @ManuBabu , as mentioned in #28, there is support in the operation context to setResponseReceivedEventHandler() to notify you every time a put block call is made but that is the extent of upload progress at this time.

I am not sure what you mean by report. Have you enabled client-side logging? https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/client-side-logging-with-the-microsoft-azure-storage-sdk-for-java

**Comment by ManuBabu** [comment]
this will help 
http://stackoverflow.com/questions/34616554/merging-multiple-azures-cloud-block-blobs-in-android
