### ISSUE TITLE
How to limit number of records (like we do in SQL) and how to give offset in TableQuery?

### ISSUE THREAD

**Issue by anandcpadiya** [Azure/azure-storage-android#45]

**Comment by jofriedm-msft** [comment]
Hi @anandcpadiya , you limit the number of records returned by passing a value for take() and pass a continuation token or select on certain values.

ie 
final ResultSegment<Class1> result = table.executeSegmented(
                TableQuery.from(Class1.class).select(new String[] { "A", "C" }).take(25), null, options, null);
result.getResults();
