### ISSUE TITLE
How to cancel the upload operation if its take too long too make connection due to slow internet ?

### ISSUE THREAD

**Issue by coderbhupendra** [Azure/azure-storage-android#46]
I used this document to upload images :[Blob uploading](https://docs.microsoft.com/en-us/azure/storage/storage-java-how-to-use-blob-storage)
But when my internet is too slow. It keeps on trying to connect. Is there any way to set timeout exception while making a connection to a container.

**Comment by jofriedm-msft** [comment]
Hi @coderbhupendra, there are two options for timeouts. MaximumExecutionTime and TimeoutInterval – the former is the total time across all retries, the latter is passed to the service as the server timeout for each request. Please take a look at https://github.com/Azure/azure-storage-java/issues/78 for more information

**Comment by coderbhupendra** [comment]
@jofriedm-msft thanks for the help. And sorry for late reply.
