### ISSUE TITLE
Event if I setTakeCount to 10 in the TableQuery, I get a result set of more than 200 Records.

### ISSUE THREAD

**Issue by anandcpadiya** [Azure/azure-storage-android#51]

**Comment by jofriedm-msft** [comment]
Hi @anandcpadiya , can you take a look at testTableQueryWithTake(...) in https://github.com/Azure/azure-storage-android/blob/master/microsoft-azure-storage-test/src/com/microsoft/azure/storage/table/TableQueryTests.java
If you are doing the same logic, can you provide repro code and what device you are testing on?

**Comment by anandcpadiya** [comment]
Worked perfectly. Thanks a lot.
I did not find any example regarding it. So putting a question was the only options for me.
It would be better if someone from your side put a perfect example of it inside https://github.com/Azure/azure-storage-android/blob/master/microsoft-azure-storage-samples/src/com/microsoft/azure/storage/samples/table/TableGettingStartedTask.java.

**Comment by jofriedm-msft** [comment]
Great! We have an open item to improve our samples #16 and are actively working on a new approach toward samples.

**Comment by jofriedm-msft** [comment]
Closing as we already have an item tracking improving samples
