### ISSUE TITLE
SAS token blob container Shared Key authentication

### ISSUE THREAD

**Issue by saio23** [Azure/azure-storage-android#78]
Hello, I was wondering what are the steps, for using a Share key authentication, instead of providing the account name and key to each user.  I am trying to use this library to share files between several users.
Can we have more detailed examples for this situations?

**Comment by gadeweever** [comment]
See: [Issue 16](https://github.com/Azure/azure-storage-android/issues/16#issuecomment-590156760) 

The last comment has an example in Kotlin using an `AsyncTask` instance.

**Comment by saio23** [comment]
> See: [Issue 16](https://github.com/Azure/azure-storage-android/issues/16#issuecomment-590156760)
> 
> The last comment has an example in Kotlin using an `AsyncTask` instance.

Thank you ! :)

**Comment by saio23** [comment]
![image](https://user-images.githubusercontent.com/61179451/75141900-9c298180-56fa-11ea-978a-bdb07e12a667.png)
I tried it this way and it worked. Thank you
```
    
 // Get SAS token from Azure Storage Explorer after creating permissions for a Blob Container , create an instance of StorageCredentialsSharedAccessSignature using the SAS token.
                StorageCredentialsSharedAccessSignature SAS_TOKEN = new StorageCredentialsSharedAccessSignature("sas_token_permissions_from_storage_explorer");
try {
  container = new CloudBlobContainer(URI.create("https://'account_name'.blob.core.windows.net/'blob_Container_name'"),SAS_TOKEN);

CloudBlockBlob blockBlob = container.getBlockBlobReference(fileName+fileType);
   
//   Same file are overwritten. Using the following if statement it creates a new file.
if (blockBlob.exists()){             
blockBlob=container.getBlockBlobReference(Calendar.getInstance().getTime()+"_"+file.getName());
}
//Upload file.
 blockBlob.uploadFromFile(stringFilePath,null,null,null);
 } catch (StorageException e) {
      e.printStackTrace();
  } catch (URISyntaxException e) {
       e.printStackTrace();
  } catch (IOException e) {
       e.printStackTrace();
  }
       
```

**Comment by AdrianxSh** [comment]
@saio23 Thanks dude, this worked for me too.
